language: emacs-lisp
before_install:
  - git submodule update --init --recursive
  - rm -rf ~/.emacs.d
  - ln -s $PWD ~/.emacs.d
  - if [ "$EMACS" = 'emacs24' ]; then
      sudo add-apt-repository -y ppa:cassou/emacs &&
      sudo apt-get update -qq &&
      sudo apt-get install -qq
          emacs24 emacs24-el emacs24-common-non-dfsg;
    fi
env:
  - EMACS=emacs24
script:
  ./run-travis-ci.sh